### ISSUE TITLE
Document expected fullview format

### ISSUE THREAD

**Issue by fluboi** [Rezopole/capstat#1]
Hi,
Current BGP fullview in the repository is pretty old. 
I didn't found any info about the exact format expected by capstat. It just look like the Cisco CLI output... and I currently don't have any fullview Cisco router.

I tried to use Hurricane Electric telnet looking glass (route-server.he.net) that provide a Cisco like output. Capstat accept my file, seems to read it, but AS are finally not correctly interpreted. 

Fullview used: [fv_20180522.zip](https://github.com/Rezopole/capstat/files/2026331/fv_20180522.zip)

Is it possible to document the expected format ? :)

**Comment by jean-daniel-pauget** [comment]
two answers here, a short one and a long one

== short ==
with the latest release of capstat, if the machine that process your capture is online, you can skip the fullview parameter, captstat will then use dns queries to retrieve the IP->AS matches.
this behaviour will be long-time supported, the fullview import being unreliable until we use a proper full-view export (json or xml)

== long ==
the expected format is the concatenation of the outputs of an Cisco's ios-xe (typically asr-1000)
for those commands:
`show ip bgp`
`show ip bgp ipv6 unicast`

sadly, it completely relies on columns and spacings being exactly as our asr1000 outputs those informations.

in order to read your full view, I processed it this way:
`cat fv_20180522.txt | sed 's/^*.i/ *>  /' | sed 's/^___Network/_____Network/' > fv_processed.txt` (with spaces instead of underscores)

you can check its importation with this "hack":
`capstat --fullview=./fv_processed.txt --dumpfv`

it will create a new file named "fullfv_dump.txt" that you can use to check wether the import worked the way you intended.

all in all, the best would be to add a new feature: json or xml import from router APIs. but this isn't scheduled in our agenda yet.

**Comment by fluboi** [comment]
Thanks for your reply.
So I do have an other problem: if I do not specify any fullview, IP-> AS via DNS queries is not working. 
My laptop do have a working, not firewall-ed, internet connectivity. 
A capture do not show any DNS queries trying to retrieve IP->AS.

Manually requesting server hardcoded [here](https://github.com/Rezopole/capstat/blob/master/capstat.cpp#L1270) with dig works. 

Capstat only show "(as-2)" for IPv6 addresses, and "(as-1)" for IPv4 ones:

```src AS repartition : 2 src AS, spread over 999451 packets
1 (as-1) 921357 92% 92%  (92% 92%  grand-total) 

src AS repartition : 2 src AS, spread over 589535652 bytes
1 (as-1) 544819226 92% 92%  (92% 92%  grand-total) 

dst AS repartition : 2 dst AS, spread over 999451 packets
1 (as-1) 921357 92% 92%  (92% 92%  grand-total) 

dst AS repartition : 2 dst AS, spread over 589535652 bytes
1 (as-1) 544819226 92% 92%  (92% 92%  grand-total) 

src/dst AS repartition : 2 src/dst AS, spread over 999451 packets
1 [ (as-1) (as-1) ] 921357 92% 92%  (92% 92%  grand-total) 

src/dst AS repartition : 2 src/dst AS, spread over 589535652 bytes
1 [ (as-1) (as-1) ] 544819226 92% 92%  (92% 92%  grand-total) 
```
Do you have any idea what could cause this behavior ? I'm using Debian Sid.

**Comment by rezopole-maint** [comment]
> Do you have any idea what could cause this behavior ? I'm using Debian Sid. 
not really, I don't have a sid over the hand to test.

a test would be to build the light "sistership" project that simply
perform the corresponding dig with almost the same dns-lib code :
https://github.com/Rezopole/asdig

it should give you such answers :

> ./asdig 134.214.100.6
2060 | 134.214.0.0/16 | EU | ripe | 1993-09-01 | FR-RENATER
> ./asdig as42
42 | US | arin | 2001-05-16 | WOODYNET-1

if not, we should look for the common troubles ...

-- 
    Jean-Daniel Pauget                         http://rezopole.net/
    Rezopole/LyonIX                            +33 (0)4 27 46 00 50

**Comment by fluboi** [comment]
asdig is correctly working. Capstat still showing "(as-2)" for IPv6 addresses, and "(as-1)" for IPv4 ones.

**Comment by jean-daniel-pauget** [comment]
okay, we'll need to dig further.
can you supply an extract of the capture that triggers the problem with the exact command line used when you encounter those troubles ?
for confidentiality and because its not related to full-table format anymore, please mail to the following email : capstat@rezopole.net

**Comment by fluboi** [comment]
I've tried to reproduce the issue in a fresh, just installed sid VM... and I do not reproduce the bug. 
It does not seems to be related to a specific capture file. 
I will try to understand what's going wrong on my laptop in the next days.

**Comment by fluboi** [comment]
Hum. 
I really do not understand what's happened... 
I checked if all the dependancies where correctly installed: 

```
sudo apt install libpcap-dev libc6-dev g++
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
g++ est déjà la version la plus récente (4:7.3.0-3).
g++ passé en « installé manuellement ».
libc6-dev est déjà la version la plus récente (2.27-3).
libc6-dev passé en « installé manuellement ».
libpcap-dev est déjà la version la plus récente (1.8.1-6).
```
--> Already OK.

Then checked if I was on the last commit

```
/capstat$ git pull
Déjà à jour.
```
Same, already OK. 
Then tried to re-compile using `make`... ... And now capstats is working properly ! 
Really strange... but not capstats fault. 
Sorry for all that noise, I probably missed that some unidentified thing went wrong during the first compile.  
Thanks for your help and time.
